taskool2/core/api/urls.py
from django.urls import path
from .views import *

app_name = 'taskilled'

urlpatterns = [
    path('course/', CourseAPIView.as_view(), name='course'),
    path('create-subject/', CreateSubjectAPIView.as_view(), name='subject'),
    path('create-promocode/', PromocodeCreateAPIView.as_view(), name='promocode'),
    path('use-promocode/', GetPromocodeDiscountAPIViev.as_view(), name='use-promocode'),
    path('all-courses/', CourseListAPIView.as_view(), name='all-courses'),
    path('all-subjects/', SubjectListAPIView.as_view(), name='all-subjects'),
    path('course/<int:id>/', CourseDetailAPIView.as_view(), name='course-detail'),
    path('subject/<int:id>/', SubjectDetailAPIView.as_view(), name='subject-detail'),
    path('question/', QuestionCreateAPIView.as_view(), name='question'),
    path('all-questions/', QuestionListAPIView.as_view(), name='all-question'),
    path('question/<int:id>/', QuestionDetailAPIView.as_view(), name='question-detail'),
    path('option/', OptionCreateAPIView.as_view(), name='option'),
    path('all-options/', OptionListAPIView.as_view(), name='all-options'),
    path('option/<int:id>/', OptionDetailAPIView.as_view(), name='option-detail'),
    path('order/', OrderCreateAPIView.as_view(), name='order'),
    path('all-order/', OrderListAPIView.as_view(), name='all-order'),
    path('order/<int:id>/', OrderDetailAPIView.as_view(), name='order-detail'),
    path('user-answer/', UserAnswerCreateAPIView.as_view(), name='user-answer'),
    path('all-user-answers/', UserAnswerListAPIView.as_view(), name='all-user-answers'),
    path('user-answer/<int:id>/', UserAnswerDetailAPIView.as_view(), name='user-answer-detail'),
    path('edit-user/<int:id>/', UserAnswerDetailAPIView.as_view(), name='user-answer-detail'),
    path('answer-type/<int:id>/', AnswerTypeDetailAPIView.as_view(), name='answer-type-detail'),
    path('rating/',RatingListCreateAPIView.as_view(),name='rating-list'),
    path('question-comments/<int:id>/', CommentAPIView.as_view(), name='comments'),
    path('course-weeks/', WeeksListAPIView.as_view(), name='course-weeks'),
    
]
    

taskool2/core/urls.py
from django.urls import path
from core.views import *
from django.contrib.auth.views import LogoutView

app_name = 'core'

urlpatterns = [
    path('',MainPageView.as_view(),name ='main'),
    path('course-list',CourseListView.as_view(),name = 'course-list'),
    path('internship-list',InternshipListView.as_view(),name = 'internship-list'),
    path('business-task-list',BTaskListView.as_view(),name = 'btask-list'),
    path('course/<int:pk>/',CourseDetailView.as_view(),name = 'course-detail'),
    path('profile',ProfileView.as_view(),name = 'profile'),
    path('student-profile',StudentProfileView.as_view(),name = 'student-profile'),
    path('quiz',QuizView.as_view(),name = 'quiz'),
    path('create-task',CreateTaskView.as_view(),name = 'create-task'),
    path('question/<int:pk>/',QuestionView.as_view(),name = 'question'),
    path('register',RegisterView.as_view(),name = 'register'),
    path('register-type',RegChooseView.as_view(),name = 'register-type'),
    path('register-student',RegStudentView.as_view(),name = 'register-student'),
    path('login',LoginView.as_view(),name = 'login'),
    path('create-course',CreateCourseView.as_view(),name = 'create-course'),
    path('create-subject',CreateSubjectView.as_view(),name = 'create-subject'),
    path('create-question',CreateQuestionView.as_view(),name = 'create-question'),
    path('create-option',CreateOptionView.as_view(),name = 'create-option'),
    path('feedback',FeedbackView.as_view(),name = 'feedback'),
    path('edit-course/<int:pk>',EditCourseView.as_view(),name = 'edit-course'),
    path('edit-question/<int:pk>',EditQuestionView.as_view(),name = 'edit-question'),
    path('course-questions/<int:pk>',CourseQuestionView.as_view(),name = 'course-questions'),
    path('edit-profile',EditProfile.as_view(),name = 'edit-profile'),
    path('congrats',CongratsPageView.as_view(),name = 'congrats'),
    path('log-out', LogoutView.as_view(), name='log-out')
]

taskool2/taskilled/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('accounts.api.urls')),
    path('', include('core.urls',namespace = 'core')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('api/v1/core/', include('core.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskool2/core/models.py
from django.db import models
from accounts.models import User
from datetime import datetime
from accounts.models import User
from django.core.mail import send_mail
import requests
import os
import xmltodict

BASE_URL = 'https://e-commerce.kapitalbank.az'
PORT='5443'

def postPay(data):
      headers = {'Content-Type': 'application/xml'} 
      r = requests.post(
            f'{BASE_URL}:{PORT}/Exec',
            data=data,
            verify=False,
            headers=headers,
            cert=(CERT_FILE, KEY_FILE)
        )
      print(r.text)
      return r.text

CERT_FILE = os.getenv("KAPITAL_CERT_FILE", "./taskilled.crt")
KEY_FILE = os.getenv("KAPITAL_KEY_FILE", "./merchant_name.key")

# Create your models here.
class Course(models.Model):
    title = models.CharField('Title',max_length=50)
    teacher = models.ForeignKey(User,on_delete=models.CASCADE, db_index=True, related_name='course_teacher')
    price = models.DecimalField('Price',max_digits=6, decimal_places=2)
    image = models.ImageField('Image',upload_to='images/')
    video = models.FileField('Video',upload_to='videos/', null=True, blank=True)
    description = models.TextField('Description')
    course_deadline = models.CharField('Deadline',blank=True,max_length=50)
    minimum_age = models.IntegerField('Minimum age',blank=True,null=False)
    is_shared = models.BooleanField('is shared',default=0)
    category = models.ForeignKey("Category", on_delete=models.CASCADE, db_index=True, related_name='category_course', null=True, blank=True)
    youtube_video_url = models.CharField('YouTube video url',max_length=1000, null=True, blank=True)
    # shared_at = models.DateTimeField('shared_at')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

    def __str__(self):
        return f"{self.title}" 
    
    def get_avg_rating(self):
        rat_numbers = list(map(lambda e: e.rating, self.ratings.all()))
        if rat_numbers:
            return sum(rat_numbers)//len(rat_numbers)
        else:
            return 0

class Category(models.Model):
    title = models.CharField('Title',max_length=50, null=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f"{self.title}" 

class Question(models.Model):
    
    title = models.CharField('Title',max_length=50)
    description = models.TextField('Description', null=True, blank=True)
    correct_answer = models.CharField('Correct answer',max_length=125,null=True,blank=True)
    image = models.ImageField('Image',upload_to='images/', null=True, blank=True)
    # video = models.FileField('Video',upload_to='videos/', null=True, blank=True)
    video = models.CharField('Video',max_length=5000, null=True, blank=True)
    edu_url = models.CharField('Url',max_length=200,null=True,default=False)
    # answer_file = models.FileField('File',upload_to='files/', null=True, blank=True)
    # audio_record = models.FileField('File',upload_to='files/', null=True, blank=True)
    answer_type = models.ManyToManyField('AnswerType',  verbose_name=("Answer Type"), db_index=True, related_name="answer_type_question", null=True, blank=True)
    week = models.IntegerField(default=1)
    
    is_auto = models.BooleanField('Is auto', default=1)
    is_success = models.BooleanField('Is succes', default=0)
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE, db_index=True, related_name='questionn', null=True)

    class Meta():
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'
    def __str__(self):
        return f"{self.title}" 

class AnswerType(models.Model):
    title = models.CharField('Title',max_length=50)

    class Meta():
        verbose_name = 'AnswerType'
        verbose_name_plural = 'AnswerTypes'

    def __str__(self):
        return f"{self.title}" 

class UserAnswer(models.Model):
    feedback = models.TextField('Feedback', null=True, blank=True)
    answer = models.TextField('Answer')
    image = models.ImageField('Image',upload_to='images/', null=True, blank=True)
    video = models.FileField('Video',upload_to='videos/', null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, db_index=True, related_name='user_answer_q')
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='user_answer')

    def save(self, *args, **kwargs):
        super(UserAnswer, self).save(*args, **kwargs)
        if self.question.is_auto == True:
            print(self.answer)
            print(self.question.id)
            print(self.question.correct_answer)
            if self.answer == self.question.correct_answer:
                self.question.is_success = True
                print('done', self.question.is_success)
            else:
                print('wrong', self.question.is_success)

    class Meta:
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='order')
    course = models.ForeignKey("Course", on_delete=models.CASCADE, db_index=True, related_name='the_order')
    promocode = models.ForeignKey("Promocode", on_delete=models.CASCADE, db_index=True, related_name='promocode_order', null=True, blank=True)
    successfuly_paid = models.BooleanField('Successfuly Paid',default=False)
    # final_price = models.DecimalField('Price',max_digits=6, decimal_places=2, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)
        # print(self.course.category.title)
        
        if self.course.category.title == "Internship":
            print('You are buying an Internship!')
            print(self.course.teacher.email)
            print(self.user)
            send_mail('Someone applied to your Internship!', f'{self.user.first_name} {self.user.last_name} applied to your Internship!\nHere is information of user:\nEmail: {self.user.email}\nPhone number: {self.user.number}', 'husubayli@gmail.com', [self.course.teacher.email,])
        
       


class Option(models.Model):
    content = models.CharField('Title',max_length=255)
    question = models.ForeignKey('Question', on_delete=models.CASCADE, db_index=True, related_name='option')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Option'
        verbose_name_plural = 'Options'

    def __str__(self):
        return f"{self.content}" 

class Subject(models.Model):
    title = models.CharField('Title',max_length=50)
    deadline = models.IntegerField('Deadline',blank=True,null=True)
    course = models.ForeignKey('Course', on_delete=models.CASCADE, db_index=True, related_name='subject')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Subject'
        verbose_name_plural = 'Subjects'

    def __str__(self):
        return f"{self.title}" 

class Rating(models.Model):
    RATING_CHOICES = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5)
    )

    author = models.ForeignKey(User,on_delete=models.CASCADE, db_index=True, related_name='ratings')
    rating = models.PositiveSmallIntegerField('rating',choices=RATING_CHOICES)
    course = models.ForeignKey("Course", on_delete=models.CASCADE, db_index=True, related_name='ratings')

    def __str__(self):
        return f'{self.author} > {self.course} rating'
    
    class Meta:
        unique_together = ('author','course')

class Promocode(models.Model):
    code = models.CharField('Code',max_length=50)
    discount_percent = models.IntegerField('Discount Percent',blank=True,null=True)

     
class Comment(models.Model):
    
    author = models.ForeignKey(User,on_delete=models.CASCADE,db_index=True, related_name='comments')
    question = models.ForeignKey(Question,on_delete=models.CASCADE,db_index=True, related_name='comments')
    content = models.CharField(max_length=255)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ("id",)
    
    def __str__(self):
        return f"{self.content}"

taskool2/core/templates/b_task.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/course_list.css' %}">
{% endblock %}

{% block content %}

<div class="course-header">

    <div style="display: flex; justify-content: space-between;">
    <h2><b>All Courses</b> </h2>
    
    <span style="margin-left: 70%;">Açar sözlər:</span>
    <div id="reset-btn-div" style="display: none; background-color: darkgray; color: white; border-radius: 5px; padding: 15px 20px;"><span id="keyword"></span>
    <button id="reset-search" style="border: none; border-radius: 50%; padding: 3px 6px; margin-left: 5px; background-color: grey; color: white; outline: none;">X</button>
    </div>
    
    </div>
    <div class="mt-3 mb-3">
        <h5 style="color: gray;"></h5>
    </div>
</div>
    <section class="section__learn_english mt-3 container-fluid">
        <div class="section__learn_english_container">
            <div class="container-fluid">
                
                <div class="col-12">
                    <div class="ml-3">
                       
                         <div class="d-flex">

                            
                            <!-- <div class="d-flex">
                                <p class="mt-3">sort by</p>
                                <div class="sort_by_btn sort_by_btn-flex"><input class="sort_by_btn__child"
                                        type="submit" value="Our recommendations "><i
                                        class="fas fa-long-arrow-alt-down text-info"></i></div>
                                <input class="sort_by_btn" type="submit" value="best reviewed">
                                <input class="sort_by_btn" type="submit" value="price">
                            </div> -->
                            
                        </div>

                        <div id="list-here" class="row"></div>

                        
                        


                    </div>

                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/b_task-list.js' %}"></script>
    {% endblock %}




    

taskool2/core/templates/congrats.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/congrats.css' %}">
{% endblock %}

{% block content %}

<div class="main mb-5">
    <div class="head">
        <h1 class="heading mb-5">Congratulations!</h1>
        <img class="happy-icon mb-5" src="{% static 'img/happycustomer.png' %}" alt="">
        <h1 class="mb-5">You have completede the course!</h1>
        <a href="{% url 'core:main' %}"><button class="back-btn">Go Back</button></a>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'js/cong.js' %}"></script>
{% endblock %}

taskool2/core/templates/edit-course.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/course_detail.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
    integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<style>
    html,
    body {
        min-height: 100%;
    }

    body,
    div,
    form,
    input,
    select,
    textarea,
    label {
        padding: 0;
        margin: 0;
        outline: none;
        font-family: Roboto, Arial, sans-serif;
        font-size: 14px;
        color: #666;
        line-height: 22px;
    }

    
    .testbox {
        width: 70%;
        margin-left: auto;
        height: inherit;
        padding: 20px;
        
    }



    .banner {
        position: relative;
        height: 300px;
        background-image: url("/uploads/media/default/0001/02/095995dadd0a1a9d5d83e6a467edf9ef7f35c114.jpeg");
        background-size: cover;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
    }

    .banner::after {
        content: "";
        background-color: rgba(0, 0, 0, 0.2);
        position: absolute;
        width: 100%;
        height: 100%;
    }

    input,
    select,
    textarea {
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    input {
        width: calc(100% - 10px);
        padding: 5px;
    }

    input[type="date"] {
        padding: 4px 5px;
    }

    textarea {
        width: calc(100% - 12px);
        padding: 5px;
    }

    .item:hover p,
    .item:hover i,
    .question:hover p,
    .question label:hover,
    input:hover::placeholder {
        color: #cc7a00;
    }

    .item input:hover,
    .item select:hover,
    .item textarea:hover {
        border: 1px solid transparent;
        box-shadow: 0 0 3px 0 #cc7a00;
        color: #cc7a00;
    }

    .item {
        position: relative;
        margin: 10px 0;
    }

    .item span {
        color: red;
    }

    input[type="date"]::-webkit-inner-spin-button {
        display: none;
    }

    .item i,
    input[type="date"]::-webkit-calendar-picker-indicator {
        position: absolute;
        font-size: 20px;
        color: #cc7a00;
    }

    .item i {
        right: 1%;
        top: 30px;
        z-index: 1;
    }

    [type="date"]::-webkit-calendar-picker-indicator {
        right: 1%;
        z-index: 2;
        opacity: 0;
        cursor: pointer;
    }

    input[type=radio],
    input[type=checkbox] {
        display: none;
    }

    label.radio {
        position: relative;
        display: inline-block;
        margin: 5px 20px 15px 0;
        cursor: pointer;
    }

    .question span {
        margin-left: 30px;
    }

    .question-answer label {
        display: block;
    }

    label.radio:before {
        content: "";
        position: absolute;
        left: 0;
        width: 17px;
        height: 17px;
        border-radius: 50%;
        border: 2px solid #ccc;
    }

    input[type=radio]:checked+label:before,
    label.radio:hover:before {
        border: 2px solid #cc7a00;
    }

    label.radio:after {
        content: "";
        position: absolute;
        top: 6px;
        left: 5px;
        width: 8px;
        height: 4px;
        border: 3px solid #cc7a00;
        border-top: none;
        border-right: none;
        transform: rotate(-45deg);
        opacity: 0;
    }

    input[type=radio]:checked+label:after {
        opacity: 1;
    }

    .btn-block {
        margin-top: 10px;
        text-align: center;
    }

    button {
        width: 150px;
        padding: 20px;
        border: none;
        border-radius: 5px;
        background: #cc7a00;
        font-size: 19px;
        color: #fff;
        cursor: pointer;
    }

    button:hover {
        background: #ff9800;
    }

    @media (min-width: 568px) {

        .name-item,
        .city-item {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .name-item input,
        .name-item div {
            width: calc(50% - 20px);
        }

        .name-item div input {
            width: 97%;
        }

        .name-item div label {
            display: block;
            padding-bottom: 5px;
        }
    }
    .main{
        height: 100VH;
        width: 100%;
    }
    .left-side {
        width: 100%;
        background-color: #343a40 !important;
        height: 100%;
        padding: 0px;
    }
    .username-name {
        width: 50%;
        height: 100% !important;
        background-color: transparent;
        color: white;
        font-size: 40px;
        margin: 0 auto;
        margin-top: 40px;
    }
    .left-list {
        height: inherit;
        margin-top: 30px;
    }

    .left-ul {
        width: 100%;
        color: white;
        font-size: 25px;
        height: 100%;
        margin: 0 auto;
    }

    .left-li {
        color: white;
        width: 60%;
        margin: 0 auto;
        display: flex;
        justify-content: left;
        font-size: 20px;
        text-transform: uppercase;
    }
    .left-li:hover{
        color: wheat;
        border: none;
        outline: none;
        text-decoration: none;
    }
</style>
{% endblock %}

{% block content %}

</head>

<body>
    <h1 id="sub-pk" class="d-none">{{subject.id}}</h1>
    <div class="main row">
        <div class="col-3 left-side">
            <div>
                <p class="username-name">Username</p>

            </div>
            <div class="left-list">
                <ul class="left-ul">
                    <li class="mt-4" style="padding: 20px; ">
                        <a href="" class="sidebar-items left-li">
                            Created
                        </a>
                    </li>
                    <li class="mt-4" style="padding: 20px; ">
                        <a href="" class="sidebar-items left-li">
                            Shared
                        </a>
                    </li>
                    <li class="mt-4" style="padding: 20px; ">
                        <a href="{% url 'core:create-course' %}" class="sidebar-items left-li">
                            Create Course
                        </a>
                    </li>
                    <li class="mt-4" style="padding: 20px; ">
                        <a href="{% url 'core:edit-profile' %}" class="sidebar-items left-li">
                            Edit Profile
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    <div class="d-none" id="pk">{{course.id}}</div>
    <div class="testbox">
        <div><h1>Edit Your course</h1></div>
        <form action="" id="courseForm">
            <div class="d-flex">
                <div class="item">
                    <label for="name">Course Name<span>*</span></label>
                        <input id="title" type="text" name="name" placeholder="" />
    
                </div>
                <div class="item">
                    <label for="description">Description<span>*</span></label>
                    <textarea name="description" id="description" cols="30" rows="1"></textarea>
                </div>
                <div class="item">
                    <label for="price">Price<span>*</span></label>
                    <input id="price" type="number" name="price" />
                </div>
            </div>
            
            <div class="item">
                <label for="age">Minimum Age<span>*</span></label>
                <input id="age" type="number" name="number" />
            </div>
            <div class="item">
                <label for="time">Course Period<span>*</span></label>
                <input id="time" type="text" name="time" />
            </div>
            <div class="item">
                <label for="time">Kursun YouTube təqdimat video linki<span></span></label>
                <input id="yt_video" type="text" name="time" />
            </div>
            <!-- <div class="item">
                <label for="image">Course picture<span>*</span></label>
                <input id="image" type="file" name="age"/>
            </div> -->
            <div class="item mb-5">
                <a href="{% url 'core:course-questions' course.pk%}" style="width: 150px;
                padding: 15px;
                border: none;
                border-radius: 5px;
                background: #cc7a00;
                font-size: 16px;
                color: #fff;
                cursor: pointer;
                text-decoration: none;">
                Questions
            </a>


            <button type="submit">Next</button>


        </form>
    </div>
    </div>

    <script src="{% static 'js/edit-course.js' %}"></script>
    {% endblock %}

taskool2/core/templates/internship_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/course_list.css' %}">
{% endblock %}

{% block content %}
<div class="course-header">

    <div style="display: flex; justify-content: space-between;">
    <h2><b>All Courses</b> </h2>
    
    <span style="margin-left: 70%;">Açar sözlər:</span>
    <div id="reset-btn-div" style="display: none; background-color: darkgray; color: white; border-radius: 5px; padding: 15px 20px;"><span id="keyword"></span>
    <button id="reset-search" style="border: none; border-radius: 50%; padding: 3px 6px; margin-left: 5px; background-color: grey; color: white; outline: none;">X</button>
    </div>
    
    </div>
    <div class="mt-3 mb-3">
        <h5 style="color: gray;"></h5>
    </div>
</div>
    <section class="section__learn_english mt-3 container-fluid">
        <div class="section__learn_english_container">
            <div class="container-fluid">
                
                <div class="col-12">
                    <div class="ml-3">
                       
                         <div class="d-flex">

                            
                            <!-- <div class="d-flex">
                                <p class="mt-3">sort by</p>
                                <div class="sort_by_btn sort_by_btn-flex"><input class="sort_by_btn__child"
                                        type="submit" value="Our recommendations "><i
                                        class="fas fa-long-arrow-alt-down text-info"></i></div>
                                <input class="sort_by_btn" type="submit" value="best reviewed">
                                <input class="sort_by_btn" type="submit" value="price">
                            </div> -->
                            
                        </div>

                        <div id="list-here" class="row"></div>

                        
                        


                    </div>

                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/internship-list.js' %}"></script>
    {% endblock %}




    

taskool2/core/templates/student_profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
<!-- <link rel="preconnect" href="https://fonts.gstatic.com" /> -->
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet" />
{% endblock %}

{% block content %}




<section class="main">
    <div class="row" style="width: 101%;">
        <div class="ulclass pt-5 col-md-2 col-12" style="background: #343a40!important;
        padding-left: 40px;">
            <ul class="lef-ul">
                <li class="mt-4">
                    <a href="{% url 'core:main' %}" style="color: white;" class="sidebar-items">
                        Ana səhifə
                    </a>
                </li>
                <li class="mt-4">
                    <a href="{% url 'core:course-list' %}" style="color: white;" class="sidebar-items">
                        Kurslar
                    </a>
                </li>
                <li class="mt-4">
                    <a style="font-size: 15px; color: white;" href="{% url 'core:edit-profile' %}" class="sidebar-items">
                        Profilində düzəliş elə
                    </a>
                </li>
            </ul>
        </div>

        <div class="col-md-8 col-12 mt-5 pl-5">
            <h2>Kurslariniz</h2>
            <div class="row created-section" id="created-section">

            </div>

            <!-- <div class="col-3 created">
                        <div class="card">
                            <div class="for-image">
                                <img src="https://cdn.mos.cms.futurecdn.net/wtqqnkYDYi2ifsWZVW2MT4-1200-80.jpg" class="card-img-top" alt="...">
                            </div>
                            <div class="card-body p-0">
                              <h5 class="card-title text-center mt-2">Some course</h5>
                            </div>
                          </div>
                    </div> -->
            <div>

            </div>
            <!-- <div class="col-3 created">
                        <div class="card" style="border: none;">
                            <div class="for-image" style="margin-top: 27%; margin-left: 8px;">
                                <img src="download.png" style="background-color: white;" class="card-img-top" alt="...">
                                
                            </div>
                          </div>
                    </div> -->

        </div>
        <div class="col-md-2 col-12 pt-5" style="background-color: rgb(244, 244, 244); border-left: 1px solid rgba(0,0,0,.1);">
            <h2 id="user-title" class="mb-4"></h2>
            <label for="user-fullname"><b>Name</b></label>
            <p id="user-fullname"></p>
            <label for="user-email"><b>Email</b></label>
            <p id="user-email"></p>
        </div>
    </div>
    </div>
</section>

<script src="{% static 'js/student_profile.js' %}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
<script>
        // ClassicEditor
        //         .create( document.querySelector( '#editor' ) )
        //         .then( editor => {
        //                 console.log( editor );
        //         } )
        //         .catch( error => {
        //                 console.error( error );
        //         } );
</script>
{% endblock %}