taskool2/core/api/urls.py
from django.urls import path
from .views import *

app_name = 'taskilled'

urlpatterns = [
    path('course/', CourseAPIView.as_view(), name='course'),
    path('create-subject/', CreateSubjectAPIView.as_view(), name='subject'),
    path('create-promocode/', PromocodeCreateAPIView.as_view(), name='promocode'),
    path('use-promocode/', GetPromocodeDiscountAPIViev.as_view(), name='use-promocode'),
    path('all-courses/', CourseListAPIView.as_view(), name='all-courses'),
    path('all-subjects/', SubjectListAPIView.as_view(), name='all-subjects'),
    path('course/<int:id>/', CourseDetailAPIView.as_view(), name='course-detail'),
    path('subject/<int:id>/', SubjectDetailAPIView.as_view(), name='subject-detail'),
    path('question/', QuestionCreateAPIView.as_view(), name='question'),
    path('all-questions/', QuestionListAPIView.as_view(), name='all-question'),
    path('question/<int:id>/', QuestionDetailAPIView.as_view(), name='question-detail'),
    path('option/', OptionCreateAPIView.as_view(), name='option'),
    path('all-options/', OptionListAPIView.as_view(), name='all-options'),
    path('option/<int:id>/', OptionDetailAPIView.as_view(), name='option-detail'),
    path('order/', OrderCreateAPIView.as_view(), name='order'),
    path('all-order/', OrderListAPIView.as_view(), name='all-order'),
    path('order/<int:id>/', OrderDetailAPIView.as_view(), name='order-detail'),
    path('user-answer/', UserAnswerCreateAPIView.as_view(), name='user-answer'),
    path('all-user-answers/', UserAnswerListAPIView.as_view(), name='all-user-answers'),
    path('user-answer/<int:id>/', UserAnswerDetailAPIView.as_view(), name='user-answer-detail'),
    path('edit-user/<int:id>/', UserAnswerDetailAPIView.as_view(), name='user-answer-detail'),
    path('answer-type/<int:id>/', AnswerTypeDetailAPIView.as_view(), name='answer-type-detail'),
    path('rating/',RatingListCreateAPIView.as_view(),name='rating-list'),
    path('question-comments/<int:id>/', CommentAPIView.as_view(), name='comments'),
    path('course-weeks/', WeeksListAPIView.as_view(), name='course-weeks'),
    
]
    

taskool2/core/urls.py
from django.urls import path
from core.views import *
from django.contrib.auth.views import LogoutView

app_name = 'core'

urlpatterns = [
    path('',MainPageView.as_view(),name ='main'),
    path('course-list',CourseListView.as_view(),name = 'course-list'),
    path('internship-list',InternshipListView.as_view(),name = 'internship-list'),
    path('business-task-list',BTaskListView.as_view(),name = 'btask-list'),
    path('course/<int:pk>/',CourseDetailView.as_view(),name = 'course-detail'),
    path('profile',ProfileView.as_view(),name = 'profile'),
    path('student-profile',StudentProfileView.as_view(),name = 'student-profile'),
    path('quiz',QuizView.as_view(),name = 'quiz'),
    path('create-task',CreateTaskView.as_view(),name = 'create-task'),
    path('question/<int:pk>/',QuestionView.as_view(),name = 'question'),
    path('register',RegisterView.as_view(),name = 'register'),
    path('register-type',RegChooseView.as_view(),name = 'register-type'),
    path('register-student',RegStudentView.as_view(),name = 'register-student'),
    path('login',LoginView.as_view(),name = 'login'),
    path('create-course',CreateCourseView.as_view(),name = 'create-course'),
    path('create-subject',CreateSubjectView.as_view(),name = 'create-subject'),
    path('create-question',CreateQuestionView.as_view(),name = 'create-question'),
    path('create-option',CreateOptionView.as_view(),name = 'create-option'),
    path('feedback',FeedbackView.as_view(),name = 'feedback'),
    path('edit-course/<int:pk>',EditCourseView.as_view(),name = 'edit-course'),
    path('edit-question/<int:pk>',EditQuestionView.as_view(),name = 'edit-question'),
    path('course-questions/<int:pk>',CourseQuestionView.as_view(),name = 'course-questions'),
    path('edit-profile',EditProfile.as_view(),name = 'edit-profile'),
    path('congrats',CongratsPageView.as_view(),name = 'congrats'),
    path('log-out', LogoutView.as_view(), name='log-out')
]

taskool2/taskilled/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('accounts.api.urls')),
    path('', include('core.urls',namespace = 'core')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('api/v1/core/', include('core.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskool2/core/api/views.py
# from typing import final
from django.db.models import query
import requests
from rest_framework import response
from rest_framework.generics import CreateAPIView, ListAPIView, ListCreateAPIView
from core.models import Course, Rating, Subject, Question , Option, Order, UserAnswer, AnswerType, Promocode, Comment
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .serializers import (
    CourseSerializer,
    RatingSerializer, 
    SubjectSerializer, 
    QuestionSerializer, 
    OptionSerializer, 
    OrderSerializer,
    UserAnswerSerializer,
    CreateCourseSerializer,
    PromocodeSerializer,
    AnswerTypeSerializer,
    CommentSerializer,
    CommentCreateSerializer
)

from rest_framework import serializers, status,permissions
from rest_framework.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
import os
import xmltodict

BASE_URL = 'https://e-commerce.kapitalbank.az'
PORT='5443'

def postPay(data):
      headers = {'Content-Type': 'application/xml'} 
      r = requests.post(
            f'{BASE_URL}:{PORT}/Exec',
            data=data,
            verify=False,
            headers=headers,
            cert=(CERT_FILE, KEY_FILE)
        )
      print(r.text)
      return r.text

CERT_FILE = os.getenv("KAPITAL_CERT_FILE", "./testmerchant.crt")
KEY_FILE = os.getenv("KAPITAL_KEY_FILE", "./merchant_name.key")

class AnswerTypeDetailAPIView(APIView):
    def get(self, request, *args, **kwargs):
        answer_type = get_object_or_404(AnswerType, pk=kwargs['id'])
        serializer = AnswerTypeSerializer(answer_type)
        return Response(serializer.data)

class CourseAPIView(CreateAPIView):
    model = Course
    serializer_class = CreateCourseSerializer

class PromocodeCreateAPIView(CreateAPIView):
    model = Promocode
    serializer_class = PromocodeSerializer

class GetPromocodeDiscountAPIViev(APIView):
    def post(self, request, *args, **kwargs):
        course_id = self.request.data.get('course')
        code = self.request.data.get('code')
        promocode = Promocode.objects.filter(code=code)
        # course = Course.objects.filter(pk=course_id)[0]
        # discount = course.price * promocode.discount_percent/100
        # new_price = course.price - discount
        print(promocode)
        # course.updat
        
        if len(promocode) == 0:
            response = False
        else:
            response = True
            final_promo = Promocode.objects.filter(code=code)[0]


        if response == True:
            return Response({
            'code_id': final_promo.id,
            'code': code,
            'message': "Promocode activated!"
            })
        else:
            return Response({
            'message': "Promocode is invalid!"
            })
            

class CourseListAPIView(ListAPIView):
    serializer_class = CourseSerializer

    def get_queryset(self):
        title = self.request.data.get('title')
        queryset = Course.objects.order_by('-id')
        print(title)

        if title:
            queryset = queryset.filter(title__icontains=title)

        return queryset

    def post(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
    
class CourseDetailAPIView(APIView):
    def get(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs['id'])
        serializer = CourseSerializer(course)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs['id'])
        serializer = CourseSerializer(course, data=request.data, partial=True)
        if serializer.is_valid():
            course = serializer.save()
            return Response(CourseSerializer(course).data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs['id'])
        course.delete()
        return Response("Course deleted", status=status.HTTP_204_NO_CONTENT)

class CreateSubjectAPIView(CreateAPIView):
    model = Subject
    serializer_class = SubjectSerializer

class SubjectListAPIView(ListAPIView):
    serializer_class = SubjectSerializer

    def get_queryset(self):
        queryset = Subject.objects.order_by('id')
        return queryset

class SubjectDetailAPIView(APIView):
    def get(self, request, *args, **kwargs):
        subject = get_object_or_404(Subject, pk=kwargs['id'])
        serializer = SubjectSerializer(subject)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        subject = get_object_or_404(Subject, pk=kwargs['id'])
        serializer = SubjectSerializer(subject, data=request.data, partial=True)
        if serializer.is_valid():
            subject = serializer.save()
            return Response(SubjectSerializer(subject).data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, *args, **kwargs):
        subject = get_object_or_404(Subject, pk=kwargs['id'])
        subject.delete()
        return Response("Subject deleted", status=status.HTTP_204_NO_CONTENT)


class QuestionCreateAPIView(CreateAPIView):
    model = Question
    serializer_class = QuestionSerializer


class QuestionListAPIView(ListAPIView):
    serializer_class = QuestionSerializer
    def get_queryset(self):
        queryset = Question.objects.order_by('id')
        return queryset


class QuestionDetailAPIView(APIView):

    def get(self, request, *args, **kwargs):
        question = get_object_or_404(Question, pk=kwargs['id'])
        serializer = QuestionSerializer(question)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        question = get_object_or_404(Question, pk=kwargs['id'])
        serializer = QuestionSerializer(question, data=request.data, partial=True)
        if serializer.is_valid():
            question = serializer.save()
            return Response(QuestionSerializer(question).data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, *args, **kwargs):
        question = get_object_or_404(Question, pk=kwargs['id'])
        question.delete()
        return Response("Question deleted", status=status.HTTP_204_NO_CONTENT)


class OptionCreateAPIView(CreateAPIView):
    model = Option
    serializer_class = OptionSerializer


class OptionListAPIView(ListAPIView):
    serializer_class = OptionSerializer
    def get_queryset(self):
        queryset = Option.objects.order_by('id')
        return queryset


class OptionDetailAPIView(APIView):

    def get(self, request, *args, **kwargs):
        option = get_object_or_404(Option, pk=kwargs['id'])
        serializer = OptionSerializer(option)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        option = get_object_or_404(Option, pk=kwargs['id'])
        serializer = OptionSerializer(option, data=request.data, partial=True)
        if serializer.is_valid():
            option = serializer.save()
            return Response(OptionSerializer(option).data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, *args, **kwargs):
        option = get_object_or_404(Option, pk=kwargs['id'])
        option.delete()
        return Response("Option deleted", status=status.HTTP_204_NO_CONTENT)


class OrderCreateAPIView(CreateAPIView):
    model = Order
    serializer_class = OrderSerializer


    def perform_create(self, serializer):
        obj = serializer.save()
        return obj.id

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        # print(serializer, 'SERIALIZER')
        serializer.is_valid(raise_exception=True)
        id = self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        # self.object = self.get_object()
        print( Order.objects.filter(pk=id), 'this is id')
        xxx = Order.objects.filter(pk=id)[0]
        print(xxx.promocode)
        course = Course.objects.get(pk=int(request.data['course']))
        price = course.price
        if xxx.promocode != None:
            discount = price * xxx.promocode.discount_percent/100
            price = price - discount
        # Order.objects.filter(pk=id).update(successfuly_paid=1)
        # order = get_object_or_404(Course, pk=request.data['user'])
        
        # 3136323935333336313333323230303030303030
        # 3136323935333431303935373030303030303030
        if price == 0:
            print('This is free!')
            free_resp = {
                'status': 'free',
                'id': id
            }
            return Response(free_resp, status=status.HTTP_201_CREATED, headers=headers)
        else:
            data = f"""<?xml version="1.0" encoding="UTF-8"?>
            <TKKPG>
                <Request>
                        <Operation>CreateOrder</Operation>
                        <Language>RU</Language>
                        <Order>
                                <OrderType>Purchase</OrderType>
                                <Merchant>E1180053</Merchant>
                                <Amount>{price*100}</Amount>
                                <Currency>944</Currency>
                                <Description>{id}</Description>
                                <ApproveURL>https://taskool.com/course/{course.id}/</ApproveURL>
                                <CancelURL>https://taskool.com/course/{course.id}/</CancelURL>
                                <DeclineURL>https://taskool.com/course/{course.id}/</DeclineURL>
                        </Order>
                </Request>
            </TKKPG>"""
        response = postPay(data)

taskool2/core/templates/includes/footer.html
<footer class="bg-dark text-center text-white mt-0 display">

    <div class="d-flex text-center footer-fst">

    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Abonə olun</strong>
              </p>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="email" id="form5Example2" class="form-control" placeholder="Email address" />
                <label class="d-none form-label" for="form5Example2">Email address</label>
              </div>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-light mb-4">
                Göndər
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
    </div>
    <div class="container pt-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="https://www.facebook.com/Taskilled"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="https://www.youtube.com/channel/UCpR0PKQcr96CUoYboBRNKKg"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-youtube"></i
        ></a>
  
        <!-- Google -->
        <!-- <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-google"></i
        ></a> -->
  
        <!-- Instagram -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="https://www.instagram.com/taskilled_com/"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <!-- <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-linkedin"></i
        ></a> -->
        <!-- Github -->
        <!-- <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-github"></i
        ></a> -->
      </section>
      <!-- Section: Social media -->
    </div>
    
  </div>

<div class="row m-0">
<div class="col-lg-3 col-md-6 mb-4 mb-md-0 mt-2 ">
  <h6 class="">Məktəblilər</h6>

  <ul class="list-unstyled mb-5">
    <li>
      <a href="{% url 'core:student-profile' %}" class="text-white">Hesabım</a>
    </li>
  </ul>
  </ul>
</div>
<div class="col-lg-3 col-md-6 mb-4 mb-md-0 mt-2 footer-scd "  style="text-align: start">
  <h6 class="">Haqqımızda</h6>

  <ul class="list-unstyled mb-5">
    <li>
      <a href="{% url 'core:student-profile' %}" class="text-white">Proqramlar</a>
    </li>
    <li>
      <a href="{% url 'core:student-profile' %}" class="text-white">Bizimlə əlaqə</a>
    </li>
  </ul>
</div>

<div class="col-lg-3 col-md-6 mb-4 mb-md-0 mt-2" style="text-align: start;">


  <ul class="list-unstyled mb-5" style="text-align: start;">
    <li class="mb-2 footer-thr">
      <a href="" class="text-white">Dərs yaratmaq</a>
    </li>
  </ul>
</div>
</div>
    <!-- Grid container -->
  
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2021 Copyright:
      <a class="text-white" href="http://taskilled.com/">Taskilled</a>
    </div>
    <!-- Copyright -->
  </footer>

taskool2/core/templates/includes/navbar.html
{% load static %}

<div class="container-fluid m-auto d-flex justify-content-center" style="background-color: #343a40!important;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-white " style="background:#343a40!important;">
  <div class="logo">
    <a href="{% url 'core:main' %}">    <img class="head-image" src="{% static 'img/TASKool.png' %}" style="width: 100%;">
    </a>  

  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-5 mt-2 mt-lg-0 ml-5">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:course-list' %}">Kurslar <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="cre-link">
        <a class="nav-link" href="{% url 'core:internship-list' %}">Oyunlar</a>
      </li>
      <li class="nav-item active" id="cre-link" >
        <a class="nav-link" href="{% url 'core:btask-list' %}">Olimpiadalar</a>
      </li>
      <li class="nav-item search-nav">
        <form action="" class="nav-search">
        <input type="text" class="nav-input" style="background-color: #343a40!important; border: 1px solid white; border-radius: 3px; padding: 7px; color: white; outline: none;" placeholder="Axtarış et">
      </form>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0 ml-5">

      <input class="d-none form-control mr-sm-2 ml-5" type="search" placeholder="Search">
      {% if user.is_authenticated %}
      <a href="/profile"><button class="btn auth-reg my-2 my-sm-0 ml-4" type="submit">{{request.user.username}}</button>
      </a>
      <a href="{% url 'core:log-out' %}">
      <button class="btn my-2 my-sm-0 ml-4" id="log-out2" type="submit">Çıxış</button>
    </a>
      {% else %}
      <a href="{% url 'core:profile' %} ">
        <div class="user-data-here">
          <a href="{% url 'core:login' %}" class="log">
            <button class="btn auth my-2 my-sm-0 ml-4" type="submit" style="color:white;">Giriş</button>
          </a>
          <a href="{%url 'core:register-type' %}">
            <button class="btn auth-reg my-2 my-sm-0 ml-4" type="submit">Qeydiyyat</button>
          </a>
          </div>
            <button class="btn my-2 my-sm-0 ml-4" id="log-out" type="submit" style="color: white;">Çıxış</button>
          
      </a>
      {% endif %}
     
    </div>

    </div>
  </div>
</nav>
</div>